/** \file egs_utils.h
 * Contains generic utilities macro / functions
 *
 * $Id: egs_utils.h,v 1.2 2004/12/08 13:26:42 besson Exp $
 */

#ifndef RY_EGS_UTILS_H
#define RY_EGS_UTILS_H

#include "nel/misc/debug.h"

/// if defined, the EGS persistant data generated by the PDS will be in debug mode
/// It should only concern dynamic_casts from PD genrated type to EGS types
#define RY_EGS_PD_DEBUG

/// assert and cast that must be used to test the PD generated class
#ifdef RY_EGS_PD_DEBUG
	#define EGS_PD_AST nlassert
	#define EGS_PD_CAST dynamic_cast
#else
	#define EGS_PD_AST ((void)0)
	#define EGS_PD_CAST static_cast
#endif

/// if USE_PDS is defined, we use the Persistant Data service, otherwise, EGS takes full care of persistance
//#define USE_PDS

#endif // egs_utils

/* End of egs_utils.h */
